{% set name = "python-flint" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 488352f6c37933bc44558502f0bfe7d0339a6cc07e97d2a1db4afc7660fa8022
  patches:
    # Make flint.h use DLL build
    - fix_win_build.diff

build:
  number: 0
  skip: true  # [py<311]
  script:
    - {{ PYTHON }} -m pip install . -Csetup-args="-Dc_args=/std:c11 /experimental:c11atomics" -vvv    # [win]
    - {{ PYTHON }} -m pip install . -Csetup-args=${MESON_ARGS// / -Csetup-args=} -vvv                                     # [unix]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - ninja                                 # [build_platform != target_platform]
    - pkg-config                            # [build_platform != target_platform]
  host:
    - python
    - cython
    - pip
    - meson-python
    - ninja
    - pkg-config
    - libflint
    - mpfr
    - pypy3.9 7.3.11  # [python_impl == "pypy"]
    - gmp
  run:
    - python

test:
  requires:
    - pypy3.9 7.3.11  # [python_impl == "pypy"]
  imports:
    - flint
  commands:
    - python -m flint.test

about:
  home: https://github.com/flintlib/python-flint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for Flint and Arb
  doc_url: https://python-flint.readthedocs.io/en/latest
  dev_url: https://github.com/flintlib/python-flint

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - jan-janssen
