{% set name = "python-flint" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0358f05548d477e23c79dbe15b2449e12e4b3d76af41fb16a4c7d035065b12cd

build:
  number: 3
  script:
    - set "INCLUDE=%INCLUDE%;%LIBRARY_INC%\\flint"  # [win]
    - {{ PYTHON }} -m pip install . --global-option=build_ext --global-option=-DMSC_USE_DLL -vvv    # [win]
    - {{ PYTHON }} -m pip install . -vvv    # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - pip                                   # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - python
    - cython
    - pip
    - numpy
    - libflint
    - mpfr
    - pypy3.9 7.3.11  # [python_impl == "pypy"]
    - gmp
  run:
    - python

test:
  requires:
    - pypy3.9 7.3.11  # [python_impl == "pypy"]
  imports:
    - flint
  commands:
    - python -m flint.test

about:
  home: https://github.com/fredrik-johansson/python-flint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python bindings for Flint and Arb
  doc_url: http://fredrikj.net/python-flint
  dev_url: https://github.com/fredrik-johansson/python-flint

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - jan-janssen
