{% set name = "python-flint" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 947573a0f7e92ac58c08ff43c3c949379a3329e52df93e8e2420fe8041c8cfbd
  patches:
    - gh9.patch
    - doctest.patch

build:
  number: 1007
  skip: True  # [win]
  script:
    - set "INCLUDE=%INCLUDE%;%LIBRARY_INC%\\flint"  # [win]
    - "{{ PYTHON }} -m pip install . --global-option=build_ext --global-option=-DMSC_USE_DLL -vvv"  # [win]
    - "{{ PYTHON }} -m pip install . -vvv"  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
    - arb
    - libflint
    - mpfr
    - mpir    # [win]
    - gmp     # [unix]
    - numpy
  run:
    - python
    - libflint
    - mpfr
    - mpir    # [win]
    - gmp     # [unix]

test:
  source_files:
    - test/test.py
  imports:
    - flint
  commands:
    - python test/test.py

about:
  home: https://github.com/fredrik-johansson/python-flint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python bindings for Flint and Arb'
  doc_url: http://fredrikj.net/python-flint
  dev_url: https://github.com/fredrik-johansson/python-flint

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - jan-janssen
